version: '3.8'

services:
  app:
    build: .
    expose:
      - "5000"
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATA_PATH=/app/data/candidate-pairs.pickle
      - RESULTS_PATH=/app/data/results.csv
      - ANNOTATION_REDUNDANCY=0
      - CONSENSUS_MARGIN=1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
